services:
  - type: worker
    name: nextecom-consumers
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: tsx scripts/start-consumers.ts
    envVars:
      - key: NODE_ENV
        value: production
      - key: RABBITMQ_URL
        fromDatabase:
          name: rabbitmq
          property: connectionString
      - key: DATABASE_URL
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: FROM_NAME
        value: "NextEcom"
      - key: ADMIN_EMAIL
        sync: false

databases:
  - name: mongodb
    plan: free
    databaseName: nextecom
  - name: rabbitmq
    plan: free
    databaseName: nextecom
